version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    network_mode: host
    restart: always
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
      - ALLOW_REGISTRATION=true
    volumes:
      - open-webui-data:/app/backend/data

volumes:
  open-webui-data:

